name: CI

on: [push, pull_request]

env:
  OPENUCX_LINK: https://github.com/openucx/ucx.git
  XCCL_LINK: https://github.com/openucx/xccl.git

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: pytorch/pytorch:latest
    steps:
    - name: Install packages
      run: |
        apt-get update
        apt-get install -y --no-install-recommends build-essential git cmake libtool-bin wget autoconf automake
        conda uninstall -y pytorch torchvision
        conda install -y pytorch torchvision cpuonly -c pytorch-nightly
    - name: Get UCX
      run: |
        git clone ${OPENUCX_LINK} /tmp/ucx
        cd /tmp/ucx
        ./autogen.sh
        ./contrib/configure-release-mt --without-java --disable-numa --prefix=/opt/ucx
        make -j install
    - name: Get XCCL
      run: |
        git clone ${XCCL_LINK} /tmp/xccl
        cd /tmp/xccl
        ./autogen.sh
        ./configure --with-ucx=/opt/ucx --prefix=/opt/xccl
        make -j install
    - uses: actions/checkout@v1
    - name: Build with UCX
      run: |
        UCX_HOME=/opt/ucx/ WITH_CUDA=no WITH_XCCL=no python setup.py install
        UCX_HOME=/opt/ucx/install python setup.py clean --all
        pip uninstall -y torch-ucc
    - name: Build with UCX and XCCL
      run: |
        UCX_HOME=/opt/ucx/ WITH_CUDA=no WITH_XCCL=/opt/xccl/ python setup.py install
    - name: Tests
      run: |
        export LD_LIBRARY_PATH=/opt/ucx/lib:/opt/xccl/lib:$LD_LIBRARY_PATH
        export TORCH_UCC_XCCL_TLS=ucx
        echo "XCCL allreduce"
        TORCH_UCC_COLL_BACKEND=xccl /bin/bash ./test/start_test.sh ./test/torch_allreduce_test.py --backend=gloo
        echo "XCCL alltoall"
        TORCH_UCC_COLL_BACKEND=xccl /bin/bash ./test/start_test.sh ./test/torch_alltoall_test.py --backend=gloo
        echo "XCCL alltoallv"
        TORCH_UCC_COLL_BACKEND=xccl /bin/bash ./test/start_test.sh ./test/torch_alltoallv_test.py --backend=gloo
        echo "XCCL barrier"
        TORCH_UCC_COLL_BACKEND=xccl /bin/bash ./test/start_test.sh ./test/torch_barrier_test.py --backend=gloo
        echo "XCCL allgather"
        TORCH_UCC_COLL_BACKEND=xccl /bin/bash ./test/start_test.sh ./test/torch_allgather_test.py --backend=gloo
        echo "XCCL broadcast"
        TORCH_UCC_COLL_BACKEND=xccl /bin/bash ./test/start_test.sh ./test/torch_bcast_test.py --backend=gloo
